name: Build and publish Docker image

on:
  repository_dispatch:
    types: [new-release]
  
jobs:
  build-and-publish:
    name: Build and publish Docker image tag ${{ github.event.client_payload.tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: stremio/server
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: VERSION=${{ github.event.client_payload.tag }}
          # Tag as latest and the `client_payload` version tag
          tags: stremio/server:${{ github.event.client_payload.tag }},stremio/server:latest
          labels: ${{ steps.meta.outputs.labels }}